export const APP = Object.freeze({
  NAME: process.env.NEXT_PUBLIC_NAME as string,
  CHAIN_ID: parseInt(process.env.NEXT_PUBLIC_CHAIN_ID as string),
  MASTER_CONTRACT: process.env.NEXT_PUBLIC_MASTER_CONTRACT as string,
  MARKET_CONTRACT: process.env.NEXT_PUBLIC_MARKET_CONTRACT as string,
  IPFS_GATEWAY: "https://storage.burningzombies.com",
  MASTER_CONTRACT_CID: process.env.NEXT_PUBLIC_MASTER_CONTRACT_CID as string,
  MARKET_CONTRACT_CID: process.env.NEXT_PUBLIC_MARKET_CONTRACT_CID as string,
  SPLITTER_CONTRACT: process.env.NEXT_PUBLIC_SPLITTER_CONTRACT as string,
  SPLITTER_CONTRACT_CID: process.env
    .NEXT_PUBLIC_SPLITTER_CONTRACT_CID as string,

  // Lottery consts
  LOTTERY_START: 1640184677,
  LOTTERY_DURATION: 60 * 60,
  LOTTERY_CONTRACT: "0x8C1A44F241c1C5Bb73ede6e9afec028E23aA398F",
  LOTTERY_CONTRACT_CID: process.env.NEXT_PUBLIC_LOTTERY_CONTRACT_CID as string,
});
